spring:
  datasource:
    url: jdbc:postgresql://192.168.0.105:5432/expense_app
    username: postgres
    password: YoniGeo2024!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'false'
          auth: 'false'
    host: 192.168.0.105
    username:
    password:
    port: '2525'

server:
  port: 8085

application:
  security:
    jwt:
      secret-key: 28482B4D6251655468576D5A7134743677397A24432646294A404E635266556A
      expiration: 3600000 # an hour
      refresh-token:
        expiration: 86400000 # a day
